import asyncHandler from "../utils/asyncHandler.js";
import ApiError from "../utils/ApiError.js";
import * as aiService from "../services/aiService.js";

const DEFAULT_LIMIT = 200;

/**
 * Deterministic layout for the graph's SVG viewBox (0 0 850 400, see
 * KnowledgeGraphPanel.jsx). The AI Engine's graph is entity/relationship
 * data only - it has no opinion on where a node should sit on screen -
 * so Express (the presentation-facing layer) computes positions here
 * rather than asking the AI Engine to own layout concerns.
 *
 * Nodes are spread evenly around concentric ellipses so the layout stays
 * readable as the real graph grows with more uploaded documents, instead
 * of a single ring becoming overcrowded.
 */
const computeLayout = (nodes) => {
    const centerX = 425;
    const centerY = 195;
    const count = nodes.length;

    if (count === 0) return [];
    if (count === 1) return [{ ...nodes[0], x: centerX, y: centerY }];

    const RING_SIZE = 18;
    const ringCount = Math.ceil(count / RING_SIZE);

    return nodes.map((node, i) => {
        const ring = Math.floor(i / RING_SIZE);
        const ringStart = ring * RING_SIZE;
        const ringNodeCount = Math.min(RING_SIZE, count - ringStart);
        const indexInRing = i - ringStart;
        const angle = (2 * Math.PI * indexInRing) / ringNodeCount - Math.PI / 2;
        const shrink = ringCount > 1 ? ring / ringCount : 0;
        const radiusX = 370 - shrink * 260;
        const radiusY = 155 - shrink * 105;

        return {
            ...node,
            x: Math.round(centerX + radiusX * Math.cos(angle)),
            y: Math.round(centerY + radiusY * Math.sin(angle)),
        };
    });
};

/**
 * Greedy walk over the live graph, starting from its most-connected node
 * (the natural "hub" for a guided tour) and stepping to the best-connected
 * unvisited neighbor at each hop. Replaces the old hand-picked demo path
 * with a real traversal computed from whatever documents have actually
 * been uploaded.
 */
const computeHeroPath = (nodes, edges, maxLength = 6) => {
    if (!nodes.length) return [];

    const adjacency = new Map(nodes.map((n) => [n.id, new Set()]));
    edges.forEach(({ source, target }) => {
        if (!adjacency.has(source) || !adjacency.has(target)) return;
        adjacency.get(source).add(target);
        adjacency.get(target).add(source);
    });

    let startId = nodes[0].id;
    let maxDegree = -1;
    for (const [id, neighbors] of adjacency) {
        if (neighbors.size > maxDegree) {
            maxDegree = neighbors.size;
            startId = id;
        }
    }

    const path = [startId];
    const visited = new Set(path);
    let current = startId;

    while (path.length < maxLength) {
        const candidates = [...(adjacency.get(current) || [])].filter((id) => !visited.has(id));
        if (!candidates.length) break;

        candidates.sort((a, b) => (adjacency.get(b)?.size || 0) - (adjacency.get(a)?.size || 0));
        const next = candidates[0];
        path.push(next);
        visited.add(next);
        current = next;
    }

    return path;
};

const toApiNode = (n) => ({ id: n.id, type: n.type, label: n.label, x: n.x, y: n.y });

/**
 * @route GET /api/graph/nodes
 * Reads the real Knowledge Graph generated by the AI Engine from uploaded
 * documents (data/knowledge_graph.json via FastAPI's /knowledge-graph/nodes),
 * not a static/seed collection. Query params (all optional, backward
 * compatible): search (label), type, page, limit.
 */
export const getGraphNodes = asyncHandler(async (req, res) => {
    const page = Math.max(parseInt(req.query.page, 10) || 1, 1);
    const limit = Math.min(parseInt(req.query.limit, 10) || DEFAULT_LIMIT, 500);
    const search = req.query.search?.trim().toLowerCase();
    const { type } = req.query;

    const { nodes: rawNodes = [] } = await aiService.getKnowledgeGraphNodes();

    let filtered = rawNodes;
    if (search) filtered = filtered.filter((n) => n.label?.toLowerCase().includes(search));
    if (type) filtered = filtered.filter((n) => n.type === type);

    const total = filtered.length;
    const paged = filtered.slice((page - 1) * limit, (page - 1) * limit + limit);

    res.json({
        success: true,
        nodes: computeLayout(paged).map(toApiNode),
        pagination: { page, limit, total, pages: Math.ceil(total / limit) },
    });
});

/**
 * @route GET /api/graph/edges
 * Query params: page, limit.
 */
export const getGraphEdges = asyncHandler(async (req, res) => {
    const page = Math.max(parseInt(req.query.page, 10) || 1, 1);
    const limit = Math.min(parseInt(req.query.limit, 10) || DEFAULT_LIMIT, 500);

    const { edges: rawEdges = [] } = await aiService.getKnowledgeGraphEdges();

    const total = rawEdges.length;
    const paged = rawEdges.slice((page - 1) * limit, (page - 1) * limit + limit);

    res.json({
        success: true,
        edges: paged.map((e) => [e.source, e.target]),
        pagination: { page, limit, total, pages: Math.ceil(total / limit) },
    });
});

/**
 * @route GET /api/graph/hero-path
 * Computed on every request from the live graph (see computeHeroPath
 * above) rather than a fixed, curated list of node ids, so it always
 * reflects whatever has actually been uploaded and processed.
 */
export const getHeroPath = asyncHandler(async (req, res) => {
    const [{ nodes: rawNodes = [] }, { edges: rawEdges = [] }] = await Promise.all([
        aiService.getKnowledgeGraphNodes(),
        aiService.getKnowledgeGraphEdges(),
    ]);

    res.json({
        success: true,
        heroPath: computeHeroPath(rawNodes, rawEdges),
    });
});

/**
 * @route GET /api/graph/nodes/:nodeId
 * @route GET /api/graph/node/:nodeId (alias, singular form)
 */
export const getNodeDetails = asyncHandler(async (req, res) => {
    const { nodeId } = req.params;

    let detail;
    try {
        detail = await aiService.getKnowledgeGraphNode(nodeId);
    } catch (error) {
        if (error.statusCode === 404) {
            throw new ApiError(404, "Node not found");
        }
        throw error;
    }

    const relatedIds = (detail.neighbors || []).map((n) => n.id);

    res.json({
        success: true,
        node: toApiNode(detail.node),
        relatedIds,
        relatedNodes: (detail.neighbors || []).map(toApiNode),
    });
});

/**
 * @route GET /api/graph/stats
 * Live node/edge counts and entity-type breakdown from the AI Engine's
 * own GraphStatistics, plus relationship-type breakdown and the count of
 * documents actually indexed into the graph.
 */
export const getGraphStats = asyncHandler(async (req, res) => {
    const { stats } = await aiService.getKnowledgeGraphStats();

    res.json({
        success: true,
        stats: {
            totalNodes: stats.total_nodes,
            totalEdges: stats.total_edges,
            byType: stats.entity_types || {},
            relationshipTypes: stats.relationship_types || {},
            documentsIndexed: stats.documentsIndexed ?? 0,
        },
    });
});
